/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BankingTerminalClient;
import javax.swing.*;
import java.io.*;
import java.net.Socket;
import java.net.SocketException;

/**
 *
 * @author student
 */
public class NewJFrame extends javax.swing.JFrame {
    String stringToServer;
    String stringFromServer;
    byte[] bytesFromServer = new byte[256];
    Socket client;
    InputStream inputStream;
    OutputStream outputStream;
    BufferedWriter bufferedWriter;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        connection = new javax.swing.JPanel();
        JLabel serverConnection = new JLabel();
        hostName = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        JLabel label_host_name = new JLabel();
        JLabel label_port = new JLabel();
        JButton connectBtn = new JButton();
        sign_up = new javax.swing.JPanel();
        JLabel sign_up_lbl = new JLabel();
        JLabel acc_num_lbl = new JLabel();
        JLabel pass_sign_up_lnl = new JLabel();
        userPasswdSign_up = new JPasswordField();
        sign_up_acc_num = new javax.swing.JTextField();
        JButton createBtn = new JButton();
        main_buttons = new javax.swing.JPanel();
        JLabel number_sum_lbl = new JLabel();
        number_sum = new javax.swing.JTextField();
        JButton infoBtn = new JButton();
        JButton getBtn = new JButton();
        JButton topBtn = new JButton();
        JButton sendBtn = new JButton();
        JScrollPane mainareaScroll = new JScrollPane();
        mainArea = new javax.swing.JTextArea();
        makeBankAcc = new javax.swing.JPanel();
        JLabel createLbl = new JLabel();
        JLabel acc_number_label = new JLabel();
        JLabel acc_pass_label = new JLabel();
        accNumber = new javax.swing.JTextField();
        JButton submitBtn = new JButton();
        accPasswd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Клиент терминала банка");
        setBackground(new java.awt.Color(255, 255, 255));
        sign_up.setVisible(false);
        main_buttons.setVisible(false);
        makeBankAcc.setVisible(false);
        connection.setBackground(new java.awt.Color(255, 253, 250));

        serverConnection.setText("Подключение к серверу");

        hostName.addActionListener(this::hostNameActionPerformed);

        port.addActionListener(this::portActionPerformed);

        label_host_name.setText("Имя хоста");

        label_port.setText("Порт");

        connectBtn.setText("Подключиться");
        connectBtn.addActionListener(this::connectBtnActionPerformed);

        javax.swing.GroupLayout connectionLayout = new javax.swing.GroupLayout(connection);
        connection.setLayout(connectionLayout);
        connectionLayout.setHorizontalGroup(
                connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(connectionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(serverConnection)
                                        .addComponent(label_port)
                                        .addGroup(connectionLayout.createSequentialGroup()
                                                .addComponent(label_host_name)
                                                .addGap(95, 95, 95)
                                                .addGroup(connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(hostName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(connectionLayout.createSequentialGroup()
                                                                .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(connectBtn)))))
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        connectionLayout.setVerticalGroup(
                connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(connectionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(serverConnection)
                                .addGap(34, 34, 34)
                                .addGroup(connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(label_host_name)
                                        .addComponent(hostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_port)
                                        .addComponent(connectBtn))
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        sign_up.setBackground(new java.awt.Color(255, 253, 250));

        sign_up_lbl.setText("Регистрация пользователя");

        acc_num_lbl.setText("Номер счёта");

        pass_sign_up_lnl.setText("Пароль");

        createBtn.setText("Подтвердить");
        createBtn.addActionListener(this::createBtnActionPerformed);



        javax.swing.GroupLayout sign_upLayout = new javax.swing.GroupLayout(sign_up);
        sign_up.setLayout(sign_upLayout);
        sign_upLayout.setHorizontalGroup(
                sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sign_upLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sign_up_lbl)
                                        .addGroup(sign_upLayout.createSequentialGroup()
                                                .addGroup(sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pass_sign_up_lnl)
                                                        .addComponent(acc_num_lbl))
                                                .addGap(78, 78, 78)
                                                .addGroup(sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(userPasswdSign_up, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                        .addComponent(sign_up_acc_num))
                                                .addGap(18, 18, 18)
                                                .addComponent(createBtn)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sign_upLayout.setVerticalGroup(
                sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sign_upLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sign_up_lbl)
                                .addGap(24, 24, 24)
                                .addGroup(sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(acc_num_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sign_up_acc_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(sign_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pass_sign_up_lnl)
                                        .addComponent(userPasswdSign_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(createBtn))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );


        main_buttons.setBackground(new java.awt.Color(255, 253, 250));

        number_sum_lbl.setText("Номер счёта/сумма");

        infoBtn.setText("Состояние");
        infoBtn.addActionListener(this::infoBtnActionPerformed);

        getBtn.setText("Снять");
        getBtn.addActionListener(this::getBtnActionPerformed);


        topBtn.setText("Пополнить");
        topBtn.addActionListener(this::topBtnActionPerformed);

        sendBtn.setText("Перевод");
        sendBtn.addActionListener(this::sendBtnActionPerformed);


        mainArea.setColumns(20);
        mainArea.setRows(5);
        mainareaScroll.setViewportView(mainArea);

        javax.swing.GroupLayout main_buttonsLayout = new javax.swing.GroupLayout(main_buttons);
        main_buttons.setLayout(main_buttonsLayout);
        main_buttonsLayout.setHorizontalGroup(
                main_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_buttonsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(main_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mainareaScroll, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(main_buttonsLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(main_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(main_buttonsLayout.createSequentialGroup()
                                                                .addComponent(infoBtn)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(getBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(topBtn)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(main_buttonsLayout.createSequentialGroup()
                                                                .addComponent(number_sum_lbl)
                                                                .addGap(32, 32, 32)
                                                                .addComponent(number_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(58, 58, 58))
        );
        main_buttonsLayout.setVerticalGroup(
                main_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(main_buttonsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(main_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(number_sum_lbl)
                                        .addComponent(number_sum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(main_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(infoBtn)
                                        .addComponent(getBtn)
                                        .addComponent(topBtn)
                                        .addComponent(sendBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(mainareaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
        );

        makeBankAcc.setBackground(new java.awt.Color(255, 253, 250));

        createLbl.setText("Создание счёта");

        acc_number_label.setText("Номер счёта");

        acc_pass_label.setText("Пароль");

        submitBtn.setText("Подтвердить");
        submitBtn.addActionListener(this::submitBtnActionPerformed);

        accPasswd.addActionListener(this::accPasswdActionPerformed);

        javax.swing.GroupLayout makeBankAccLayout = new javax.swing.GroupLayout(makeBankAcc);
        makeBankAcc.setLayout(makeBankAccLayout);
        makeBankAccLayout.setHorizontalGroup(
                makeBankAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(makeBankAccLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(makeBankAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(createLbl)
                                        .addGroup(makeBankAccLayout.createSequentialGroup()
                                                .addGroup(makeBankAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(acc_number_label)
                                                        .addComponent(acc_pass_label))
                                                .addGap(82, 82, 82)
                                                .addGroup(makeBankAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(accNumber)
                                                        .addComponent(accPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(submitBtn)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        makeBankAccLayout.setVerticalGroup(
                makeBankAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(makeBankAccLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createLbl)
                                .addGap(26, 26, 26)
                                .addGroup(makeBankAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(acc_number_label)
                                        .addComponent(accNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(makeBankAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(acc_pass_label)
                                        .addComponent(submitBtn)
                                        .addComponent(accPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(connection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(makeBankAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(main_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(connection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(makeBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(main_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }





    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            //соединение сокета и создание потоков
            client = new Socket (hostName.getText(),Integer.parseInt( port.getText()));
            inputStream = client.getInputStream();
            outputStream = client.getOutputStream();
            bufferedWriter = new BufferedWriter(new OutputStreamWriter(outputStream));

            sign_up.setVisible(true);
            makeBankAcc.setVisible(true);
            main_buttons.setVisible(true);
            connection.setVisible(false);

        }
        catch (SocketException ex) {
            ex.printStackTrace();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {
        stringToServer = "create " + accNumber.getText() + " " + accPasswd.getText() + "\n";

        try {
            bufferedWriter.write(stringToServer);
            bufferedWriter.flush();
            int counter = inputStream.read(bytesFromServer);
            stringFromServer = new String(bytesFromServer, 0, counter);
            stringFromServer = stringFromServer + "\n";
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
        mainArea.append(stringFromServer);
    }
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {
        stringToServer = "open " + sign_up_acc_num.getText() + " " + userPasswdSign_up.getText() + "\n";
        try {
            bufferedWriter.write(stringToServer);
            bufferedWriter.flush();
            int counter = inputStream.read(bytesFromServer);
            stringFromServer = new String(bytesFromServer, 0, counter);
            stringFromServer = stringFromServer + "\n";
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
        mainArea.append(stringFromServer);
    }

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {
        stringToServer = "view\n";
        String serverOut;
        try {
            bufferedWriter.write(stringToServer);
            bufferedWriter.flush();
            int counter = inputStream.read(bytesFromServer);
            serverOut = new String(bytesFromServer, 0, counter);
            serverOut = serverOut + "\n";
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
        mainArea.append(serverOut);
    }

    private void getBtnActionPerformed(java.awt.event.ActionEvent evt) {
        stringToServer = "get " + number_sum.getText() + "\n";
        try {
            bufferedWriter.write(stringToServer);
            bufferedWriter.flush();
            int counter = inputStream.read(bytesFromServer);
            stringFromServer = new String(bytesFromServer, 0, counter);
            stringFromServer = stringFromServer + "\n";
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
        mainArea.append(stringFromServer);
    }

    private void topBtnActionPerformed(java.awt.event.ActionEvent evt) {
        stringToServer = "put " + number_sum.getText() + "\n";
        try {
            bufferedWriter.write(stringToServer);
            bufferedWriter.flush();
            int counter = inputStream.read(bytesFromServer);
            stringFromServer = new String(bytesFromServer, 0, counter);
            stringFromServer = stringFromServer + "\n";
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
        mainArea.append(stringFromServer);
    }

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String tmpStr = number_sum.getText();
        String[] words = tmpStr.split(" ");
        stringToServer = "send " + words[0] + " " + words[1] + "\n";

        try {
            bufferedWriter.write(stringToServer);
            bufferedWriter.flush();
            int counter = inputStream.read(bytesFromServer);
            stringFromServer = new String(bytesFromServer, 0, counter);
            stringFromServer = stringFromServer + "\n";
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
        mainArea.append(stringFromServer);
    }
    private void portActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void hostNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void accPasswdActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }





    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField accNumber;
    private javax.swing.JPasswordField accPasswd;
    private javax.swing.JPanel connection;
    private javax.swing.JTextField hostName;
    private javax.swing.JTextArea mainArea;
    private javax.swing.JPanel main_buttons;
    private javax.swing.JPanel makeBankAcc;
    private javax.swing.JTextField number_sum;
    private javax.swing.JTextField port;
    private javax.swing.JPanel sign_up;
    private javax.swing.JTextField sign_up_acc_num;

    private javax.swing.JPasswordField userPasswdSign_up;


    // End of variables declaration
}
